# .gitpod.yml
# https://gitpod.io/#https://github.com/ibtisam-iq/certification-practice-vault

image: gitpod/workspace-python-3.12

tasks:
  - name: MkDocs Dev Server
    init: pip install -r requirements.txt
    command: mkdocs serve --dev-addr=0.0.0.0:8000

ports:
  - port: 8000
    onOpen: open-preview
    visibility: public

vscode:
  extensions:
    - yzhang.markdown-all-in-one
    - davidanson.vscode-markdownlint
    - streetsidesoftware.code-spell-checker
    - github.vscode-pull-request-github
    - redhat.vscode-yaml
